name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      input_data:
        description: 'Input data'
        required: true
        default: 'azureml:diabetes-folder:1'
      regularization_rate:
        description: 'Regularization rate'
        required: true
        default: 0.1 

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="rg-dp100-labs"
        az configure --defaults workspace="mlw-dp100-labs"
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml --training_data azureml:diabetes-folder:1 --reg_rate "${{ github.event.inputs.regularization_rate }}"
